main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required
class CommentForm(FlaskForm):
    description = TextAreaField('',validators=[Required()])
	submit = SubmitField()
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about your self.',validators = [Required()])
    submit = SubmitField('Submit')
class BlogForm(FlaskForm):
    title = StringField('Blog',validators=[Required()])
    description = TextAreaField('Blog Description', validators=[Required()]) 
    submit = SubmitField('Submit')

main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

main/views.py
from . import main
from flask_login import login_required
from flask import render_template,request,redirect,url_for,abort
from ..models import *
from .forms import BlogForm,UpdateProfile, CommentForm,UpdateBlogForm
from .. import db,photos
from .. requests import get_quotes
from flask_login import login_required, current_user

import markdown2 
@main.route('/blog/<int:id>')
def single_blog(id):
    Blog=Blog.query.get(id)
    if blog is None:
        abort(404)
    format_blog = markdown2.markdown(blog.blog,extras=["code-friendly", "fenced-code-blocks"])
    return render_template('blog.html',blog = blog,format_blog=format_blog)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    get_blogs = Blog.query.filter_by(user_id = current_user.id).all()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user, blog_category = get_blogs)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/update/<int:id>',methods= ['GET','POST'])
@login_required
def update_blog(id):

    blogs = Blog.query.filter_by(id = id).first()
    if blogs.user!=current_user:
        abort(404)

    form = UpdateBlogForm()

    if form.validate_on_submit():

        blogs.title = form.title.data
        blogs.description = form.description.data

        db.session.add(blogs)
        db.session.commit()

        return redirect(url_for('main.index'))
    elif request.method=='GET':
            form.description.data=blogs.description
            form.title.data=blogs.title
    return render_template('updateblog.html',form = form)

@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    quotes = get_quotes()
    blogs = Blog.query.all()
    return render_template('index.html',blogs=blogs,quotes = quotes)    


@main.route('/blog/new/', methods = ['GET','POST'])
@login_required
def new_blog():
    form = BlogForm()
    blogs = Blog.query.all()
    if form.validate_on_submit():
        description = form.description.data
        title = form.title.data
        author_id = current_user
        print(current_user._get_current_object().id)
        new_blog = Blog(user_id =current_user._get_current_object().id, title = title,description=description)#,category=category)
        db.session.add(new_blog)
        db.session.commit()

        return redirect(url_for('main.index' ))
    return render_template('blog.html',form=form,blogs=blogs)



@main.route('/comment/new/<int:blog_id>', methods = ['GET','POST'])
@login_required
def new_comment(blog_id):
    form = CommentForm()
    blog=Blog.query.get(blog_id)
    if form.validate_on_submit():
        description = form.description.data
        new_comment = Comment(description = description, user_id = current_user._get_current_object().id, blog_id = blog_id)#user_id=user_id,
        db.session.add(new_comment)
        db.session.commit()


        return redirect(url_for('.new_comment', blog_id= blog_id))

    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    return render_template('comments.html', form = form, comment = all_comments, blog = blog )


@main.route('/index/<int:id>/delete', methods = ['GET','POST'])
@login_required
def delete(id):
    current_post = Blog.query.filter_by(id = id).first()

    if current_post.user != current_user:
        abort(404)
    db.session.delete(current_post)
    db.session.commit()
    return redirect(url_for('.index'))

@main.route('/index/<int:id>/delete_comment', methods = ['GET','POST'])
@login_required
def delete_comment(id):

    current_post = Comment.query.filter_by(id = id).first()

    if current_post.user != current_user:
        abort(404)

    db.session.delete(current_post)
    db.session.commit()
    return redirect(url_for('.index'))
    return render_template('comments.html',current_post = current_post)

templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  
  {{ simplemde.css}}
  {{ simplemde.js }}
{% endblock %}

templates/blog.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% include 'navbar.html'%}
{% block content %}
{% block styles%}
{{ super() }}
{% endblock %}
<div class="container">
	<div class="row">

		{{wtf.quick_form(form)}}
		<ul style="list-style: none;">
				<h3>Mypersonal-blogs</h3>
			{% for blog in blogs %}
			
			<div class="list-group">

				<div class="list-item" style="border-radius: 15px; cursive;font-size: 20px;">
					
					{{blog.id}}.

					{{ blog.description }}
				</div>

			</div>
			{% endfor %}
		</ul>

	</div>
</div>


{% endblock %}

templates/comments.html
{% include 'navbar.html'%}

{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% import 'macros.html' as macro %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="card">
                <h4><a> Title:{{blog.title}}</a></h4>
                <h5>{{blog.description}}.</h5>
            
        </div>

        {{wtf.quick_form(form)}}

        <hr>
        <hr>
        <div class="container " style="text-align: center;">
            <div class="col-md-12 ">
             <h4>Comments</h4>

            </div>

        </div>

    </div>
</div>

{% endblock %}

templates/fourowfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>That page can't be displayed</h1>
{% endblock %}

templates/index.html
{% extends 'bootstrap/base.html' %}
{% import 'macros.html' as macro %}
{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}
{% block content %}


<div class="container" style="background-image: url(https://previews.123rf.com/images/elosa/elosa1501/elosa150100094/35351038-purpel-label-with-white-ribbon-and-english-life-quote-time-for-me-with-three-white-marguerite-blosso.jpg); background-repeat: no-repeat; background-size: cover;">
    <div class="row">
        <div class="col-sm-3">
            
                <h1>Quotes</h1>
                <p><i>{{ quotes.quote }}</i></p>
                <p>~{{ quotes.author }}</p>
{% endblock %

templates/macros.html
{% macro displayBlog(blog_List) %}
<div class="row">
    {% if blog_List %}
    {% for blog in blog_List %}
        <div class="text-center">
            <p>Title:{{blog.title}}</p>

                <h2>{{blog.description}}</h2>
                <h3>{{blog.user.username}}</h3>
                <h4>{{blog.comments.count()}}</h4>
                <a href="{{url_for('main.new_comment',blog_id = blog.id)}}"></a>
                <a href="{{url_for('main.update_blog',id = blog.id)}}"></a>
                <a href="{{url_for('main.delete',id = blog.id)}}"></a>
        </div>

    </div>
    {% endfor %}
    {% else %}
    {% endif %}
</div>
{% endmacro %}

{% macro displayComment(comments) %}
<ul>

    {% if comments %}
    {% for comment in comments %}
            <h2>{{ comment.description }}</h2>
        posted by {{comment.user.username}}
        <a href="{{url_for('main.delete_comment',id = comment.id)}}"></a>
    {% endfor %}
    {% else %}

    <h3>This post does not does not have any comments!</h3>
    {%endif%}

</ul>

{% endmacro %}

templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home </a></li>
            </ul>
            <ul>
                <a class="navbar-brand" href="/blog/new/"> Posta Blog </a>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>

    </div>

</div>
<ul>
    <h1 style="margin-top:50px; margin-bottom:50px;text-align:center; text-transform:capitalize;color:rgb(10, 10, 10);font-size:62px;font-family: 'Great Vibes', cursive; ">welcome
        to my blog </h1>
</ul>

templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    

    <!--Display profile photo-->
    <div class="col-md-4">

      {% if user.profile_pic_path %}
      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
    </div>
    <!-- displaying  Username-->
    <div class="col-md-4">
        <h3> {{user.username| capitalize}} </h3>
  
        <!--Displaying user bio-->
        {% if user.bio %}
        <p> {{user.bio}}</p>
        {%else%}
        <p> {{user.username| capitalize}} has no bio </p>
        {% endif %}
      </div>
  </div>
</div>
{% if user == current_user %}
<a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}

<div class="col-md-4">
  
  {% if user == current_user %}
  <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

    <input type="file" name="photo" class="form-control" required>
    <input type="submit">
  </form>
  {% endif %}

  
</div>

{% endblock %}

templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}